"""add name field to user model

Revision ID: 701ed117153c
Revises: 3fbb244363a8
Create Date: 2020-09-13 20:21:00.042319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701ed117153c'
down_revision = '3fbb244363a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
